<?php

/**
 * @file
 * Install hooks for this module.
 */


/**
 * Implements hook_install().
 */
function islandora_cdpv_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_cdpv');
}

/**
 * Implements hook_uninstall().
 */
function islandora_cdpv_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_cdpv', 'uninstall');
 }
